import type { PlanResult } from "./plannerEngine";
import { DIMENSIONS } from "./plannerEngine";

export const WATERMARK =
  "GENERATED BY METIS SYSTEMS // ARCHITECTURE_CORE_V1 // UNIFIED_PLAN";

function formatBriefSection(result: PlanResult): string[] {
  const { brief } = result;
  return [
    "INTENT BRIEF",
    "-----------",
    `Category: ${brief.category.replace(/_/g, " ")}`,
    `Budget: ${brief.budget}`,
    `Deployment: ${brief.deployment}`,
    `Privacy priority: ${brief.privacyPriority ? "yes" : "no"}`,
    `Code comfort: ${brief.codeComfort}`,
    brief.hardwareHint ? `Hardware hint: ${brief.hardwareHint}` : "",
    brief.keywords.length ? `Keywords: ${brief.keywords.join(", ")}` : "",
    "",
  ].filter(Boolean);
}

function formatRankedSection(result: PlanResult): string[] {
  const lines: string[] = ["RANKED RECOMMENDATIONS", "---------------------"];
  result.ranked.forEach((rec, i) => {
    lines.push(
      `${i + 1}. ${rec.candidate.name} (score: ${rec.total})`,
      `   ${rec.candidate.summary}`,
      `   Hardware tier: ${rec.candidate.hardwareTier}`,
    );
    rec.rationale.forEach((r) => lines.push(`   — ${r}`));
    lines.push("");
  });
  return lines;
}

export function toPlainText(result: PlanResult): string {
  const lines = [
    WATERMARK,
    "",
    ...formatBriefSection(result),
    ...formatRankedSection(result),
    `Primary recommendation: ${result.primaryRecommendationId}`,
    `Computed hardware tier: ${result.computedHardwareTier}`,
    "",
    WATERMARK,
  ];
  return lines.join("\n");
}

export function toMarkdown(result: PlanResult): string {
  const { brief } = result;
  const lines = [
    `> ${WATERMARK}`,
    "",
    "## Intent Brief",
    "",
    `| Field | Value |`,
    `| --- | --- |`,
    `| Category | ${brief.category.replace(/_/g, " ")} |`,
    `| Budget | ${brief.budget} |`,
    `| Deployment | ${brief.deployment} |`,
    `| Privacy priority | ${brief.privacyPriority ? "yes" : "no"} |`,
    `| Code comfort | ${brief.codeComfort} |`,
    brief.hardwareHint ? `| Hardware hint | ${brief.hardwareHint} |` : "",
    "",
    "## Ranked Recommendations",
    "",
  ].filter(Boolean);

  result.ranked.forEach((rec, i) => {
    lines.push(
      `### ${i + 1}. ${rec.candidate.name}`,
      "",
      `**Score:** ${rec.total} · **Hardware tier:** ${rec.candidate.hardwareTier}`,
      "",
      rec.candidate.summary,
      "",
      "**Rationale:**",
      ...rec.rationale.map((r) => `- ${r}`),
      "",
    );
  });

  lines.push(
    `**Primary recommendation:** \`${result.primaryRecommendationId}\``,
    `**Computed hardware tier:** \`${result.computedHardwareTier}\``,
    "",
    `---`,
    `*${WATERMARK}*`,
  );

  return lines.join("\n");
}

export function toPrintHTML(result: PlanResult): string {
  const { brief } = result;
  const rankedHtml = result.ranked
    .map(
      (rec, i) => `
    <article class="rec">
      <h3>${i + 1}. ${escapeHtml(rec.candidate.name)}</h3>
      <p class="meta">Score: ${rec.total} · Hardware: ${escapeHtml(rec.candidate.hardwareTier)}</p>
      <p>${escapeHtml(rec.candidate.summary)}</p>
      <ul>${rec.rationale.map((r) => `<li>${escapeHtml(r)}</li>`).join("")}</ul>
    </article>`,
    )
    .join("");

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>Metis Unified Plan</title>
  <style>
    * { border-radius: 0; box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: "IBM Plex Mono", monospace; background: #111; color: #F5F5F3; padding: 2rem; font-size: 12px; line-height: 1.6; }
    h1, h2, h3 { font-family: "Newsreader", serif; font-weight: 500; }
    h1 { font-size: 1.5rem; margin-bottom: 0.5rem; }
    h2 { font-size: 1.125rem; margin: 1.5rem 0 0.75rem; border-bottom: 1px solid rgba(245,245,243,0.15); padding-bottom: 0.5rem; }
    .watermark { color: #D4C5B9; font-size: 10px; letter-spacing: 0.1em; margin-bottom: 1.5rem; }
    .brief dt { color: rgba(245,245,243,0.65); margin-top: 0.35rem; }
    .brief dd { margin-left: 0; }
    .rec { border: 1px solid rgba(245,245,243,0.15); padding: 1rem; margin-bottom: 1rem; }
    .meta { color: #D4C5B9; font-size: 10px; margin: 0.35rem 0 0.5rem; }
    ul { margin: 0.5rem 0 0 1rem; color: rgba(245,245,243,0.65); }
    @media print { body { background: #fff; color: #111; } .watermark { color: #666; } }
  </style>
</head>
<body>
  <p class="watermark">${escapeHtml(WATERMARK)}</p>
  <h1>Metis Unified Plan</h1>
  <h2>Intent Brief</h2>
  <dl class="brief">
    <dt>Category</dt><dd>${escapeHtml(brief.category.replace(/_/g, " "))}</dd>
    <dt>Budget</dt><dd>${escapeHtml(brief.budget)}</dd>
    <dt>Deployment</dt><dd>${escapeHtml(brief.deployment)}</dd>
    <dt>Privacy priority</dt><dd>${brief.privacyPriority ? "yes" : "no"}</dd>
    <dt>Code comfort</dt><dd>${escapeHtml(brief.codeComfort)}</dd>
    ${brief.hardwareHint ? `<dt>Hardware hint</dt><dd>${escapeHtml(brief.hardwareHint)}</dd>` : ""}
  </dl>
  <h2>Ranked Recommendations</h2>
  ${rankedHtml}
  <p class="meta">Primary: ${escapeHtml(result.primaryRecommendationId)} · Tier: ${escapeHtml(result.computedHardwareTier)}</p>
  <p class="watermark">${escapeHtml(WATERMARK)}</p>
</body>
</html>`;
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

export function toClaudePrompt(result: PlanResult): string {
  const dimLines = DIMENSIONS.map((d) => `- ${d}`).join("\n");
  return `${WATERMARK}

You are reviewing a Metis architecture plan compiled from operator intent.

## Context
The following plan was generated by the Metis deterministic scoring engine from a plain-language brief. Use it as ground truth for follow-on architecture work.

## Intent Brief
${JSON.stringify(result.brief, null, 2)}

## Primary Recommendation
ID: ${result.primaryRecommendationId}
Hardware tier: ${result.computedHardwareTier}

## Full Ranking
${result.ranked
  .map(
    (r, i) =>
      `${i + 1}. ${r.candidate.name} (${r.total})\n   ${r.candidate.summary}\n   Rationale: ${r.rationale.join("; ")}`,
  )
  .join("\n\n")}

## Scoring Dimensions Reference
${dimLines}

## Task
Expand the primary recommendation into a phased implementation outline with infrastructure, security, and operational checkpoints. Preserve the privacy and deployment constraints from the brief.

${WATERMARK}`;
}

export function toChatGPTPrompt(result: PlanResult): string {
  return `${WATERMARK}

Review this Metis unified architecture plan and produce a concise implementation roadmap.

--- PLAN DATA ---
${toPlainText(result)}
--- END PLAN DATA ---

Instructions:
1. Summarize the top recommendation in one paragraph.
2. List three risks tied to the stated budget and deployment mode.
3. Propose a 30/60/90-day milestone table.
4. Flag any dimension scores below 6 that need mitigation.

${WATERMARK}`;
}

export type ExportFormat =
  | "plaintext"
  | "markdown"
  | "html"
  | "claude"
  | "chatgpt";

export function exportPlan(
  result: PlanResult,
  format: ExportFormat,
): string {
  switch (format) {
    case "plaintext":
      return toPlainText(result);
    case "markdown":
      return toMarkdown(result);
    case "html":
      return toPrintHTML(result);
    case "claude":
      return toClaudePrompt(result);
    case "chatgpt":
      return toChatGPTPrompt(result);
  }
}
